version: "3.8"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=replica1.crjnbxdyxzyl.us-east-1.rds.amazonaws.com
      - POSTGRES_USER=distribuidos
      - POSTGRES_PASSWORD=distribuidos
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
