# Generated by Django 3.0.5 on 2020-10-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstoretia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicas',
            name='fuel_price',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='markdown1',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='markdown2',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='markdown3',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='markdown4',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='markdown5',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='weekly_sales',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
        ),
    ]
