# Generated by Django 3.0.5 on 2020-10-07 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstoretia', '0002_auto_20201006_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracteristicas',
            old_name='isHoliday',
            new_name='isholiday',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='isHoliday',
            new_name='isholiday',
        ),
    ]
