# Generated by Django 3.0.5 on 2020-10-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstoretia', '0004_auto_20201006_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicas',
            name='cpi',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=16),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='fuel_price',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='unemployme',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
