# Generated by Django 3.0.5 on 2020-10-07 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstoretia', '0005_auto_20201006_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicas',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstoretia.Tiendas'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appstoretia.Tiendas'),
        ),
    ]
