# Generated by Django 3.0.5 on 2020-10-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstoretia', '0006_auto_20201006_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiendas',
            name='id',
        ),
        migrations.AlterField(
            model_name='tiendas',
            name='store',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
