# Generated by Django 3.0.5 on 2020-10-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstoretia', '0007_auto_20201007_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendas',
            name='size',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=10),
        ),
    ]
