# Generated by Django 3.0.5 on 2020-10-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstoretia', '0010_auto_20201010_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicas',
            name='cpi',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristicas',
            name='unemployme',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
